# Generated by Django 3.2.6 on 2021-09-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mobile',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
