# Generated by Django 3.2.6 on 2021-09-06 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_book_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='mobile',
            new_name='image',
        ),
    ]
